// Auto-generated from EXERCISE_LIST_IN_APP_VERSION_3.docx — one tutorial link per exercise.
export const EXERCISE_LINKS = {
  "Barbell Bench Press": "https://www.youtube.com/watch?v=rT7DgCr-3pg",
  "Incline Barbell Press": "https://www.youtube.com/watch?v=SrqOu55lrYU",
  "Floor Press": "https://www.youtube.com/watch?v=uUGDRwge4F8",
  "Dumbbell Bench Press": "https://www.youtube.com/watch?v=Y_7aHqXeCfQ",
  "Incline Dumbbell Press": "https://www.youtube.com/watch?v=hChjZQhX1Ls",
  "Dumbbell Flyes": "https://www.youtube.com/watch?v=QwuUZ5wgQOk",
  "Dumbbell Incline Flyes": "https://www.youtube.com/watch?v=JSDpq14vCZ8",
  "Smith Machine Bench Press": "https://www.youtube.com/watch?v=z_r6hDOYtO0",
  "Cable Crossovers": "https://www.youtube.com/watch?v=QcTcWpkn_bw",
  "Pec Deck Flyes": "https://www.youtube.com/watch?v=R63UajjKfnM",
  "Low to High Cable Flyes": "https://www.youtube.com/watch?v=eQ_NBB6OBH4",
  "Decline Cable Flyes": "https://www.youtube.com/watch?v=TR4FdOs_7PY",
  "Dips": "https://www.youtube.com/watch?v=KoS_NMmuxMM",
  "Weighted Push-Ups": "https://www.youtube.com/watch?v=hbTWvtJDQjU",
  "Deficit Push-Ups": "https://www.youtube.com/watch?v=KadL9HpmWSg",
  "Feet-Elevated Push-Ups": "https://www.youtube.com/watch?v=J21Glo_IuCI",
  "Tricep Cable Pushdowns": "https://www.youtube.com/watch?v=_w-HpW70nSQ",
  "Overhead Tricep Extensions": "https://www.youtube.com/watch?v=57fWTQID-1Y",
  "Skull Crushers": "https://www.youtube.com/watch?v=9baX4-wEYx8",
  "Close-Grip Bench Press": "https://www.youtube.com/watch?v=cXbSJHtjrQQ",
  "Single-Arm Cable Tricep Kickbacks": "https://www.youtube.com/watch?v=ZvF4Oi_6Vtg",
  "Cross-Body Cable Tricep Extensions": "https://www.youtube.com/watch?v=xzs9RTtt5y8",
  "Diamond Push-Ups": "https://www.youtube.com/watch?v=J0DXDObCTe8",
  "Dumbbell Hammer Curls": "https://www.youtube.com/watch?v=zC3nLlEvin4",
  "Barbell Bicep Curls": "https://www.youtube.com/watch?v=QZEqB6wUPxQ",
  "Incline Dumbbell Curls": "https://www.youtube.com/watch?v=soxrZlIl35U",
  "Chin-Ups": "https://www.youtube.com/watch?v=x_67qHaINQs",
  "Preacher Curls": "https://www.youtube.com/watch?v=fIWP-FRFNU0",
  "Concentration Curls": "https://www.youtube.com/watch?v=0AUGkch3tzc",
  "Cable Bayesian Curls": "https://www.youtube.com/watch?v=0W2pk4rhfd8",
  "Barbell Overhead Press": "https://www.youtube.com/watch?v=ZXpdJOLNoWw",
  "Push Press": "https://www.youtube.com/watch?v=ep30avTSMB0",
  "Barbell Clean and Press": "https://www.youtube.com/watch?v=KCe8l86-alA",
  "Dumbbell Shoulder Press": "https://www.youtube.com/watch?v=qEwKCR5JCog",
  "Seated Dumbbell Press": "https://www.youtube.com/watch?v=s_aK83TWYkA",
  "Arnold Press": "https://www.youtube.com/watch?v=6Z15_WdXmVw",
  "Lateral Raises": "https://www.youtube.com/watch?v=3VcKaXpzqRo",
  "Front Raises": "https://www.youtube.com/watch?v=-t7fuZ0KhDA",
  "Single-Arm Landmine Press": "https://www.youtube.com/watch?v=9OW4SONxuGI",
  "Cable Lateral Raises": "https://www.youtube.com/watch?v=Z5FA9aq3L6A",
  "Face Pulls": "https://www.youtube.com/watch?v=0Po47vvj9g4",
  "Reverse Pec Deck": "https://www.youtube.com/watch?v=R63UajjKfnM",
  "Pike Push-Ups": "https://www.youtube.com/watch?v=RmKUhj62_9c",
  "Handstand Push-Ups": "https://www.youtube.com/watch?v=KEfazWGOUok",
  "Barbell Rows": "https://www.youtube.com/watch?v=9efgcAjQe7E",
  "Yates Rows": "https://www.youtube.com/watch?v=sNidAp7RWU4",
  "Dumbbell Rows": "https://www.youtube.com/watch?v=pYcpY20QaE8",
  "Meadows Rows": "https://www.youtube.com/watch?v=EsmIWi_0lio",
  "Lat Pulldowns": "https://www.youtube.com/watch?v=CAwf7n6Luuc",
  "Close-Grip Lat Pulldowns": "https://www.youtube.com/watch?v=mUoo2l-p8Hw",
  "Seated Cable Rows": "https://www.youtube.com/watch?v=XaHV_8Nbyug",
  "Single-Arm Cable Rows": "https://www.youtube.com/watch?v=NwyhyKyFgf4",
  "Pull-Ups": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
  "Pendlay Rows": "https://www.youtube.com/watch?v=h4nkoayPFWw",
  "Rack Pulls": "https://www.youtube.com/watch?v=aAjN8zS7Idg",
  "Chest-Supported Dumbbell Rows": "https://www.youtube.com/watch?v=_b6ch2nIchk",
  "T-Bar Rows": "https://www.youtube.com/watch?v=TyLoy3n_a10",
  "Chest-Supported Machine Rows": "https://www.youtube.com/watch?v=zL7JWm_beA8",
  "Inverted Rows": "https://www.youtube.com/watch?v=hXTc1mDnZCw",
  "Barbell Back Squats": "https://www.youtube.com/watch?v=SW_C1A-rejs",
  "Barbell Front Squats": "https://www.youtube.com/watch?v=0ect9ETE6t0",
  "Zercher Squats": "https://www.youtube.com/watch?v=vpy4ADmlo1E",
  "Bulgarian Split Squats": "https://www.youtube.com/watch?v=-4LVK1crLSw",
  "Goblet Squats": "https://www.youtube.com/watch?v=Pz-mEGJKwWQ",
  "Walking Lunges": "https://www.youtube.com/watch?v=Oh5ziYGlgoI",
  "Step-Ups": "https://www.youtube.com/watch?v=dQqApCGd5Ss",
  "Cossack Squats": "https://www.youtube.com/watch?v=JaCbmoDqUc4",
  "Leg Press": "https://www.youtube.com/watch?v=-lAnEGH2blE",
  "Hack Squats": "https://www.youtube.com/watch?v=hrciyIRwFzs",
  "Smith Machine Squats": "https://www.youtube.com/watch?v=z_r6hDOYtO0",
  "Leg Extensions": "https://www.youtube.com/watch?v=z_2iod9ZfnY",
  "Single-Leg Extensions": "https://www.youtube.com/watch?v=z_2iod9ZfnY",
  "Sissy Squats": "https://www.youtube.com/watch?v=W6osqAEKHJs",
  "Wall Sits": "https://www.youtube.com/watch?v=y-wV4Venusw",
  "Conventional Deadlifts": "https://www.youtube.com/watch?v=VL5Ab0T07e4",
  "Sumo Deadlifts": "https://www.youtube.com/watch?v=JbY72Him34Q",
  "Romanian Deadlifts": "https://www.youtube.com/watch?v=uhghy9pFIPY",
  "Stiff-Legged Deadlifts": "https://www.youtube.com/watch?v=1uDiW5--rAE",
  "Barbell Hip Thrusts": "https://www.youtube.com/watch?v=pBH7pKHn-dI",
  "Barbell Glute Bridges": "https://www.youtube.com/watch?v=DQv1IMQDbE4",
  "Good Mornings": "https://www.youtube.com/watch?v=f23vXjoG2e8",
  "Back Extensions": "https://www.youtube.com/watch?v=Bw9YuQTTc58",
  "Reverse Lunges": "https://www.youtube.com/watch?v=Oh5ziYGlgoI",
  "Single-Leg RDLs": "https://www.youtube.com/watch?v=Zfr6wizR8rs",
  "Lying Leg Curls": "https://www.youtube.com/watch?v=vl5nUdE9mWM",
  "Seated Leg Curls": "https://www.youtube.com/watch?v=M7xxlCVQqvU",
  "Standing Single-Leg Curls": "https://www.youtube.com/watch?v=5xR8tvg4-yM",
  "Seated Calf Raises": "https://www.youtube.com/watch?v=tlECTzekxoM",
  "Standing Calf Raises": "https://www.youtube.com/watch?v=TGJCEMqTPY4",
  "Cable Pull-Throughs": "https://www.youtube.com/watch?v=yXopOhzEoeo",
  "Cable Glute Kickbacks": "https://www.youtube.com/watch?v=OV8FGnvsOOE",
  "GHD Raises": "https://www.youtube.com/watch?v=ixr4_1POpzg",
  "Hyperextensions": "https://www.youtube.com/watch?v=II_XND-grLo",
  "Single-Leg Glute Bridges": "https://www.youtube.com/watch?v=Zb3ILLdI6fk",
  "Weighted Ab Crunches": "https://www.youtube.com/watch?v=mkE_gNDQN8o",
  "Hanging Leg Raises": "https://www.youtube.com/watch?v=Pr1ieGZ5atk",
  "Ab Wheel Rollouts": "https://www.youtube.com/watch?v=yBg4UoOXxLo",
  "Dragon Flys": "https://www.youtube.com/watch?v=pvz7k5gO-DE",
  "Muscle-Ups": "https://www.youtube.com/watch?v=BbkFT3HlrIg",

  // ── Chest ────────────────────────────────────────────────────────────
  "Decline Dumbbell Press": "https://www.youtube.com/watch?v=KYJgQZPwGS8",
  "Landmine Press": "https://www.youtube.com/watch?v=9OW4SONxuGI",

  // ── Shoulders ────────────────────────────────────────────────────────
  "Dumbbell Upright Rows": "https://www.youtube.com/watch?v=K0dYqPCaO14",
  "Dumbbell Rear Delt Flyes": "https://www.youtube.com/watch?v=j4Too5fVKLY",
  "Cable Upright Rows": "https://www.youtube.com/watch?v=jaAV-rD45I0",

  // ── Biceps ───────────────────────────────────────────────────────────
  "EZ Bar Curls": "https://www.youtube.com/watch?v=5NsFLGUf0Fo",
  "Spider Curls": "https://www.youtube.com/watch?v=CITtSuda0Fg",
  "Reverse Curls": "https://www.youtube.com/watch?v=10AFVfSUzsU",
  "Cross Body Hammer Curls": "https://www.youtube.com/watch?v=zC3nLlEvin4",

  // ── Triceps ──────────────────────────────────────────────────────────
  "Bench Dips": "https://www.youtube.com/watch?v=c3ZGl4pnLZs",
  "Rope Overhead Tricep Extensions": "https://www.youtube.com/watch?v=57fWTQID-1Y",

  // ── Lats ─────────────────────────────────────────────────────────────
  "Straight-Arm Lat Pulldowns": "https://www.youtube.com/watch?v=WDOV2PDpkiU",
  "Wide-Grip Pull-Ups": "https://www.youtube.com/watch?v=eGo4IYlbE5g",

  // ── Rhomboids & Upper Back ───────────────────────────────────────────
  "Seal Rows": "https://www.youtube.com/watch?v=49Hbk_5fhoI",
  "Renegade Rows": "https://www.youtube.com/watch?v=4qEIChzM4ZA",
  "Cable Face Pulls (Rope)": "https://www.youtube.com/watch?v=0Po47vvj9g4",

  // ── Quads ────────────────────────────────────────────────────────────
  "Box Squats": "https://www.youtube.com/watch?v=WGjf5w8iaTM",
  "Cyclist Squats": "https://www.youtube.com/watch?v=0xmVi6jpYyA",
  "Pause Squats": "https://www.youtube.com/watch?v=_87_VfKY3Jg",
  "Reverse Lunges (Weighted)": "https://www.youtube.com/watch?v=Oh5ziYGlgoI",

  // ── Hamstrings / Glutes ──────────────────────────────────────────────
  "Trap Bar Deadlifts": "https://www.youtube.com/watch?v=tpUKFfIFG24",
  "Jefferson Curls": "https://www.youtube.com/watch?v=N2BVDX9Mkbc",

  // ── Chest (added) ────────────────────────────────────────────────────
  "Svend Press": "https://www.youtube.com/watch?v=cIoUZOnypS8",
  "Single-Arm Cable Chest Press": "https://www.youtube.com/watch?v=D9e8ZBlFPBw",
  "Guillotine Press": "https://www.youtube.com/watch?v=y90T12sTukg",

  // ── Shoulders (added) ────────────────────────────────────────────────
  "Cable Y-Raises": "https://www.youtube.com/watch?v=NBkMIWWkIKQ",
  "Bus Drivers": "https://www.youtube.com/watch?v=AGjuA82-10c",

  // ── Biceps (added) ───────────────────────────────────────────────────
  "Zottman Curls": "https://www.youtube.com/watch?v=KhXiqxGxu1s",
  "21s Bicep Curls": "https://www.youtube.com/watch?v=oq7jXQP3Fk8",

  // ── Triceps (added) ──────────────────────────────────────────────────
  "JM Press": "https://www.youtube.com/watch?v=FjkZpK8JhO8",
  "Tate Press": "https://www.youtube.com/watch?v=c86r5KVF7Xo",

  // ── Calisthenics (added) ─────────────────────────────────────────────
  "Push-Ups": "https://www.youtube.com/watch?v=es_Tz8Si75o",
  "Decline Push-Ups": "https://www.youtube.com/watch?v=QBlYp-EwHlo",
  "Wide Push-Ups": "https://www.youtube.com/watch?v=Z8nUVpSZAhE",
  "Chest Dips": "https://www.youtube.com/watch?v=yN6Q1UI_xkE",
  "Pseudo Planche Push-Ups": "https://www.youtube.com/watch?v=i-gSmqe9tNw",
  "Ring Push-Ups": "https://www.youtube.com/watch?v=7FRwuB1_l7U",
  "Handstand Push-Ups (wall)": "https://www.youtube.com/watch?v=kbCRcsS55LM",
  "Close Push-Ups": "https://www.youtube.com/watch?v=F1Lq9LnyvVc",
  "Hollow Body Hold": "https://www.youtube.com/watch?v=0yPin8hSc8o",

  // ── Legs (added) ─────────────────────────────────────────────────────
  "Nordic Hamstring Curls": "https://www.youtube.com/watch?v=6NCN6kOagfY",
  "Single-Leg Press": "https://www.youtube.com/watch?v=x4vaHXRfKrg",
  "Belt Squats": "https://www.youtube.com/watch?v=NaJiMZZD3Xw",

  // ── Abs & Core ───────────────────────────────────────────────────────
  "Cable Crunches": "https://www.youtube.com/watch?v=AV5PmZJIrrw",
  "Russian Twists": "https://www.youtube.com/watch?v=TfTUk2AjV7g",
  "Pallof Press": "https://www.youtube.com/watch?v=axgv7H_VQOo",
  "Dead Bug": "https://www.youtube.com/watch?v=bxn9FBrt4-A",

  // ── Added exercises (search links, not individually curated) ──────────
  // These map to a YouTube search for the exercise rather than one hand-
  // picked video like the entries above. Curating 180 individual videos
  // one-by-one wasn't practical in one pass, and guessing a specific video
  // ID without checking it risks linking to the wrong exercise entirely —
  // a working search is more reliable than an unverified guess. Swap any
  // of these for a specific video link anytime; the app doesn't care which.
  "1-Arm Lat Pull-In": "https://www.youtube.com/results?search_query=1-Arm%20Lat%20Pull-In%20exercise%20tutorial",
  "Ab Wheel Rollout": "https://www.youtube.com/results?search_query=Ab%20Wheel%20Rollout%20exercise%20tutorial",
  "Arm-Out Single-Arm DB Row": "https://www.youtube.com/results?search_query=Arm-Out%20Single-Arm%20DB%20Row%20exercise%20tutorial",
  "Arms-Extended 45° Hyperextension": "https://www.youtube.com/results?search_query=Arms-Extended%2045%C2%B0%20Hyperextension%20exercise%20tutorial",
  "Assisted Pull-Up": "https://www.youtube.com/results?search_query=Assisted%20Pull-Up%20exercise%20tutorial",
  "Barbell JM Press": "https://www.youtube.com/results?search_query=Barbell%20JM%20Press%20exercise%20tutorial",
  "Barbell Lunge": "https://www.youtube.com/results?search_query=Barbell%20Lunge%20exercise%20tutorial",
  "Bayesian Cable Curl": "https://www.youtube.com/results?search_query=Bayesian%20Cable%20Curl%20exercise%20tutorial",
  "Belt Squat": "https://www.youtube.com/results?search_query=Belt%20Squat%20exercise%20tutorial",
  "Bench Dip": "https://www.youtube.com/results?search_query=Bench%20Dip%20exercise%20tutorial",
  "Bent-Over Cable Pec Flye": "https://www.youtube.com/results?search_query=Bent-Over%20Cable%20Pec%20Flye%20exercise%20tutorial",
  "Bent-Over Cable Pec Flye (w/ Integrated Partials)": "https://www.youtube.com/results?search_query=Bent-Over%20Cable%20Pec%20Flye%20%28w/%20Integrated%20Partials%29%20exercise%20tutorial",
  "Bent-Over Reverse DB Flye": "https://www.youtube.com/results?search_query=Bent-Over%20Reverse%20DB%20Flye%20exercise%20tutorial",
  "Bent-Over Reverse DB Flye (w/ Integrated Partials)": "https://www.youtube.com/results?search_query=Bent-Over%20Reverse%20DB%20Flye%20%28w/%20Integrated%20Partials%29%20exercise%20tutorial",
  "Bicycle Crunch": "https://www.youtube.com/results?search_query=Bicycle%20Crunch%20exercise%20tutorial",
  "Bodyweight Dip": "https://www.youtube.com/results?search_query=Bodyweight%20Dip%20exercise%20tutorial",
  "Bottom-2/3 Constant Tension Preacher Curl": "https://www.youtube.com/results?search_query=Bottom-2/3%20Constant%20Tension%20Preacher%20Curl%20exercise%20tutorial",
  "Bottom-2/3 EZ-Bar Curl": "https://www.youtube.com/results?search_query=Bottom-2/3%20EZ-Bar%20Curl%20exercise%20tutorial",
  "Cable Crunch": "https://www.youtube.com/results?search_query=Cable%20Crunch%20exercise%20tutorial",
  "Cable Hip Abduction": "https://www.youtube.com/watch?v=bGlm-qTnfTI",
  "Cable Hip Adduction": "https://www.youtube.com/results?search_query=Cable%20Hip%20Adduction%20exercise%20tutorial",
  "Cable Paused Shrug-In": "https://www.youtube.com/results?search_query=Cable%20Paused%20Shrug-In%20exercise%20tutorial",
  "Cable Reverse Flye (Mechanical Dropset)": "https://www.youtube.com/results?search_query=Cable%20Reverse%20Flye%20%28Mechanical%20Dropset%29%20exercise%20tutorial",
  "Cable Shoulder Press": "https://www.youtube.com/results?search_query=Cable%20Shoulder%20Press%20exercise%20tutorial",
  "Cable Skull Crusher": "https://www.youtube.com/results?search_query=Cable%20Skull%20Crusher%20exercise%20tutorial",
  "Cable Triceps Kickback": "https://www.youtube.com/results?search_query=Cable%20Triceps%20Kickback%20exercise%20tutorial",
  "Cable Upright Row": "https://www.youtube.com/results?search_query=Cable%20Upright%20Row%20exercise%20tutorial",
  "Chest-Supported Machine Row": "https://www.youtube.com/results?search_query=Chest-Supported%20Machine%20Row%20exercise%20tutorial",
  "Chest-Supported T-Bar Row": "https://www.youtube.com/results?search_query=Chest-Supported%20T-Bar%20Row%20exercise%20tutorial",
  "Chest-Supported T-Bar Row + Kelso Shrug": "https://www.youtube.com/results?search_query=Chest-Supported%20T-Bar%20Row%20%2B%20Kelso%20Shrug%20exercise%20tutorial",
  "Close-Grip Assisted Dip": "https://www.youtube.com/results?search_query=Close-Grip%20Assisted%20Dip%20exercise%20tutorial",
  "Close-Grip Push-Up": "https://www.youtube.com/results?search_query=Close-Grip%20Push-Up%20exercise%20tutorial",
  "Concentration Cable Curl": "https://www.youtube.com/results?search_query=Concentration%20Cable%20Curl%20exercise%20tutorial",
  "Copenhagen Hip Adduction": "https://www.youtube.com/results?search_query=Copenhagen%20Hip%20Adduction%20exercise%20tutorial",
  "Cross-Body Cable Y-Raise": "https://www.youtube.com/results?search_query=Cross-Body%20Cable%20Y-Raise%20exercise%20tutorial",
  "Cross-Body Lat Pull-Around": "https://www.youtube.com/results?search_query=Cross-Body%20Lat%20Pull-Around%20exercise%20tutorial",
  "Cuffed Behind-The-Back Lateral Raise": "https://www.youtube.com/results?search_query=Cuffed%20Behind-The-Back%20Lateral%20Raise%20exercise%20tutorial",
  "DB Bulgarian Split Squat": "https://www.youtube.com/results?search_query=DB%20Bulgarian%20Split%20Squat%20exercise%20tutorial",
  "DB Calf Jumps": "https://www.youtube.com/results?search_query=DB%20Calf%20Jumps%20exercise%20tutorial",
  "DB Concentration Curl": "https://www.youtube.com/results?search_query=DB%20Concentration%20Curl%20exercise%20tutorial",
  "DB Flye": "https://www.youtube.com/results?search_query=DB%20Flye%20exercise%20tutorial",
  "DB Flye (w/ Integrated Partials)": "https://www.youtube.com/results?search_query=DB%20Flye%20%28w/%20Integrated%20Partials%29%20exercise%20tutorial",
  "DB French Press": "https://www.youtube.com/results?search_query=DB%20French%20Press%20exercise%20tutorial",
  "DB Incline Curl": "https://www.youtube.com/results?search_query=DB%20Incline%20Curl%20exercise%20tutorial",
  "DB Lat Pullover": "https://www.youtube.com/results?search_query=DB%20Lat%20Pullover%20exercise%20tutorial",
  "DB Lateral Raise": "https://www.youtube.com/results?search_query=DB%20Lateral%20Raise%20exercise%20tutorial",
  "DB Preacher Curl": "https://www.youtube.com/results?search_query=DB%20Preacher%20Curl%20exercise%20tutorial",
  "DB RDL": "https://www.youtube.com/results?search_query=DB%20RDL%20exercise%20tutorial",
  "DB Rear Delt Swing": "https://www.youtube.com/results?search_query=DB%20Rear%20Delt%20Swing%20exercise%20tutorial",
  "DB Reverse Lunge": "https://www.youtube.com/results?search_query=DB%20Reverse%20Lunge%20exercise%20tutorial",
  "DB Scott Curl": "https://www.youtube.com/results?search_query=DB%20Scott%20Curl%20exercise%20tutorial",
  "DB Shrug": "https://www.youtube.com/results?search_query=DB%20Shrug%20exercise%20tutorial",
  "DB Skull Crusher": "https://www.youtube.com/results?search_query=DB%20Skull%20Crusher%20exercise%20tutorial",
  "DB Step-Up": "https://www.youtube.com/results?search_query=DB%20Step-Up%20exercise%20tutorial",
  "DB Triceps Kickback": "https://www.youtube.com/results?search_query=DB%20Triceps%20Kickback%20exercise%20tutorial",
  "DB Walking Lunge": "https://www.youtube.com/results?search_query=DB%20Walking%20Lunge%20exercise%20tutorial",
  "Decline Barbell Press": "https://www.youtube.com/results?search_query=Decline%20Barbell%20Press%20exercise%20tutorial",
  "Decline Machine Chest Press": "https://www.youtube.com/results?search_query=Decline%20Machine%20Chest%20Press%20exercise%20tutorial",
  "Machine Chest Press": "https://www.youtube.com/watch?v=pLofEAcfsO8",
  "Decline Smith Machine Press": "https://www.youtube.com/results?search_query=Decline%20Smith%20Machine%20Press%20exercise%20tutorial",
  "Deficit Pushup": "https://www.youtube.com/results?search_query=Deficit%20Pushup%20exercise%20tutorial",
  "Donkey Calf Raise": "https://www.youtube.com/results?search_query=Donkey%20Calf%20Raise%20exercise%20tutorial",
  "Dual-Cable Triceps Press": "https://www.youtube.com/results?search_query=Dual-Cable%20Triceps%20Press%20exercise%20tutorial",
  "Dual-Handle Lat Pulldown (Mid-back + Lats)": "https://www.youtube.com/results?search_query=Dual-Handle%20Lat%20Pulldown%20%28Mid-back%20%2B%20Lats%29%20exercise%20tutorial",
  "EZ-Bar Skull Crusher": "https://www.youtube.com/results?search_query=EZ-Bar%20Skull%20Crusher%20exercise%20tutorial",
  "Elbows-In 1-Arm DB Row": "https://www.youtube.com/results?search_query=Elbows-In%201-Arm%20DB%20Row%20exercise%20tutorial",
  "Fat-Grip DB Curl": "https://www.youtube.com/results?search_query=Fat-Grip%20DB%20Curl%20exercise%20tutorial",
  "Fat-Grip Preacher Curl": "https://www.youtube.com/results?search_query=Fat-Grip%20Preacher%20Curl%20exercise%20tutorial",
  "Floor Skull Crusher": "https://www.youtube.com/results?search_query=Floor%20Skull%20Crusher%20exercise%20tutorial",
  "Front Squat": "https://www.youtube.com/results?search_query=Front%20Squat%20exercise%20tutorial",
  "Glute-Ham Raise": "https://www.youtube.com/results?search_query=Glute-Ham%20Raise%20exercise%20tutorial",
  "Goblet Squat": "https://www.youtube.com/results?search_query=Goblet%20Squat%20exercise%20tutorial",
  "Good Morning (Light Weight)": "https://www.youtube.com/results?search_query=Good%20Morning%20%28Light%20Weight%29%20exercise%20tutorial",
  "Hack Squat": "https://www.youtube.com/results?search_query=Hack%20Squat%20exercise%20tutorial",
  "Half-Kneeling 1-Arm Lat Pulldown": "https://www.youtube.com/results?search_query=Half-Kneeling%201-Arm%20Lat%20Pulldown%20exercise%20tutorial",
  "Half-Kneeling Pallof Press": "https://www.youtube.com/results?search_query=Half-Kneeling%20Pallof%20Press%20exercise%20tutorial",
  "Hammer Curl": "https://www.youtube.com/results?search_query=Hammer%20Curl%20exercise%20tutorial",
  "Hammer Preacher Curl": "https://www.youtube.com/results?search_query=Hammer%20Preacher%20Curl%20exercise%20tutorial",
  "Hanging Leg Raise": "https://www.youtube.com/results?search_query=Hanging%20Leg%20Raise%20exercise%20tutorial",
  "Helms Row": "https://www.youtube.com/results?search_query=Helms%20Row%20exercise%20tutorial",
  "High-Bar Back Squat": "https://www.youtube.com/results?search_query=High-Bar%20Back%20Squat%20exercise%20tutorial",
  "Incline Chest-Supported DB Row + Kelso Shrug": "https://www.youtube.com/results?search_query=Incline%20Chest-Supported%20DB%20Row%20%2B%20Kelso%20Shrug%20exercise%20tutorial",
  "Incline DB Stretch-Curl": "https://www.youtube.com/results?search_query=Incline%20DB%20Stretch-Curl%20exercise%20tutorial",
  "Inverse DB Zottman Curl": "https://www.youtube.com/results?search_query=Inverse%20DB%20Zottman%20Curl%20exercise%20tutorial",
  "Katana Triceps Extension": "https://www.youtube.com/results?search_query=Katana%20Triceps%20Extension%20exercise%20tutorial",
  "Kneeling Overhead Cable Curl": "https://www.youtube.com/results?search_query=Kneeling%20Overhead%20Cable%20Curl%20exercise%20tutorial",
  "LLPT Plank": "https://www.youtube.com/results?search_query=LLPT%20Plank%20exercise%20tutorial",
  "Lat Pulldown": "https://www.youtube.com/results?search_query=Lat%20Pulldown%20exercise%20tutorial",
  "Lat-Focused Cable Row": "https://www.youtube.com/results?search_query=Lat-Focused%20Cable%20Row%20exercise%20tutorial",
  "Lateral Band Walk": "https://www.youtube.com/results?search_query=Lateral%20Band%20Walk%20exercise%20tutorial",
  "Lean-Back Lat Pulldown": "https://www.youtube.com/results?search_query=Lean-Back%20Lat%20Pulldown%20exercise%20tutorial",
  "Lean-Back Machine Pulldown": "https://www.youtube.com/results?search_query=Lean-Back%20Machine%20Pulldown%20exercise%20tutorial",
  "Leg Extension": "https://www.youtube.com/results?search_query=Leg%20Extension%20exercise%20tutorial",
  "Leg Press Calf Jumps": "https://www.youtube.com/results?search_query=Leg%20Press%20Calf%20Jumps%20exercise%20tutorial",
  "Leg Press Calf Press": "https://www.youtube.com/results?search_query=Leg%20Press%20Calf%20Press%20exercise%20tutorial",
  "Low Incline Barbell Press": "https://www.youtube.com/results?search_query=Low%20Incline%20Barbell%20Press%20exercise%20tutorial",
  "Low Incline Chest Machine Press": "https://www.youtube.com/results?search_query=Low%20Incline%20Chest%20Machine%20Press%20exercise%20tutorial",
  "Low Incline DB Press": "https://www.youtube.com/results?search_query=Low%20Incline%20DB%20Press%20exercise%20tutorial",
  "Low Incline Machine Press": "https://www.youtube.com/results?search_query=Low%20Incline%20Machine%20Press%20exercise%20tutorial",
  "Low Incline Smith Machine Press": "https://www.youtube.com/results?search_query=Low%20Incline%20Smith%20Machine%20Press%20exercise%20tutorial",
  "Low-Incline Dumbbell Flye": "https://www.youtube.com/results?search_query=Low-Incline%20Dumbbell%20Flye%20exercise%20tutorial",
  "Low-To-High Cable Crossover": "https://www.youtube.com/results?search_query=Low-To-High%20Cable%20Crossover%20exercise%20tutorial",
  "Lying Leg Curl": "https://www.youtube.com/results?search_query=Lying%20Leg%20Curl%20exercise%20tutorial",
  "Lying Paused Rope Face Pull": "https://www.youtube.com/results?search_query=Lying%20Paused%20Rope%20Face%20Pull%20exercise%20tutorial",
  "Machine Chest-Supported Row + Kelso Shrug": "https://www.youtube.com/results?search_query=Machine%20Chest-Supported%20Row%20%2B%20Kelso%20Shrug%20exercise%20tutorial",
  "Machine Crunch": "https://www.youtube.com/results?search_query=Machine%20Crunch%20exercise%20tutorial",
  "Machine Hip Abduction": "https://www.youtube.com/watch?v=soaTR1UtEw0",
  "Machine Hip Adduction": "https://www.youtube.com/results?search_query=Machine%20Hip%20Adduction%20exercise%20tutorial",
  "Machine Lat Pullover": "https://www.youtube.com/results?search_query=Machine%20Lat%20Pullover%20exercise%20tutorial",
  "Machine Lateral Raise": "https://www.youtube.com/results?search_query=Machine%20Lateral%20Raise%20exercise%20tutorial",
  "Machine Pulldown": "https://www.youtube.com/results?search_query=Machine%20Pulldown%20exercise%20tutorial",
  "Machine Shoulder Press": "https://www.youtube.com/results?search_query=Machine%20Shoulder%20Press%20exercise%20tutorial",
  "Machine Shrug": "https://www.youtube.com/results?search_query=Machine%20Shrug%20exercise%20tutorial",
  "Machine Squat": "https://www.youtube.com/results?search_query=Machine%20Squat%20exercise%20tutorial",
  "Medicine Ball Russian Twists": "https://www.youtube.com/results?search_query=Medicine%20Ball%20Russian%20Twists%20exercise%20tutorial",
  "Medium-Grip Pull-Up": "https://www.youtube.com/results?search_query=Medium-Grip%20Pull-Up%20exercise%20tutorial",
  "N1-Style Short-Head Curl": "https://www.youtube.com/results?search_query=N1-Style%20Short-Head%20Curl%20exercise%20tutorial",
  "Neutral-Grip Lat Pulldown": "https://www.youtube.com/results?search_query=Neutral-Grip%20Lat%20Pulldown%20exercise%20tutorial",
  "Neutral-Grip Pull-Up": "https://www.youtube.com/results?search_query=Neutral-Grip%20Pull-Up%20exercise%20tutorial",
  "Nordic Ham Curl": "https://www.youtube.com/results?search_query=Nordic%20Ham%20Curl%20exercise%20tutorial",
  "Overhand Lat Pulldown": "https://www.youtube.com/results?search_query=Overhand%20Lat%20Pulldown%20exercise%20tutorial",
  "Overhand Machine Row": "https://www.youtube.com/results?search_query=Overhand%20Machine%20Row%20exercise%20tutorial",
  "Overhead Cable Curl": "https://www.youtube.com/results?search_query=Overhead%20Cable%20Curl%20exercise%20tutorial",
  "Overhead Cable Triceps Extension (Bar)": "https://www.youtube.com/results?search_query=Overhead%20Cable%20Triceps%20Extension%20%28Bar%29%20exercise%20tutorial",
  "Overhead Cable Triceps Extension (Rope)": "https://www.youtube.com/results?search_query=Overhead%20Cable%20Triceps%20Extension%20%28Rope%29%20exercise%20tutorial",
  "Paused Assisted Dip": "https://www.youtube.com/results?search_query=Paused%20Assisted%20Dip%20exercise%20tutorial",
  "Paused Barbell RDL": "https://www.youtube.com/results?search_query=Paused%20Barbell%20RDL%20exercise%20tutorial",
  "Paused DB RDL": "https://www.youtube.com/results?search_query=Paused%20DB%20RDL%20exercise%20tutorial",
  "Pec Deck": "https://www.youtube.com/results?search_query=Pec%20Deck%20exercise%20tutorial",
  "Pec Deck (w/ Integrated Partials)": "https://www.youtube.com/results?search_query=Pec%20Deck%20%28w/%20Integrated%20Partials%29%20exercise%20tutorial",
  "Plate-Loaded Neck Curls": "https://www.youtube.com/results?search_query=Plate-Loaded%20Neck%20Curls%20exercise%20tutorial",
  "Plate-Weighted Crunch": "https://www.youtube.com/results?search_query=Plate-Weighted%20Crunch%20exercise%20tutorial",
  "Prisoner 45° Hyperextension": "https://www.youtube.com/results?search_query=Prisoner%2045%C2%B0%20Hyperextension%20exercise%20tutorial",
  "Pull-Up": "https://www.youtube.com/results?search_query=Pull-Up%20exercise%20tutorial",
  "Rear Delt 45° Cable Flye": "https://www.youtube.com/results?search_query=Rear%20Delt%2045%C2%B0%20Cable%20Flye%20exercise%20tutorial",
  "Reverse Cable Flye": "https://www.youtube.com/results?search_query=Reverse%20Cable%20Flye%20exercise%20tutorial",
  "Reverse Cable Flye (w/ Integrated Partials)": "https://www.youtube.com/results?search_query=Reverse%20Cable%20Flye%20%28w/%20Integrated%20Partials%29%20exercise%20tutorial",
  "Reverse Crunch": "https://www.youtube.com/results?search_query=Reverse%20Crunch%20exercise%20tutorial",
  "Reverse Nordic": "https://www.youtube.com/results?search_query=Reverse%20Nordic%20exercise%20tutorial",
  "Reverse Pec Deck (w/ Integrated Partials)": "https://www.youtube.com/results?search_query=Reverse%20Pec%20Deck%20%28w/%20Integrated%20Partials%29%20exercise%20tutorial",
  "Reverse-Grip Cable Curl": "https://www.youtube.com/results?search_query=Reverse-Grip%20Cable%20Curl%20exercise%20tutorial",
  "Reverse-Grip DB Curl": "https://www.youtube.com/results?search_query=Reverse-Grip%20DB%20Curl%20exercise%20tutorial",
  "Reverse-Grip EZ-Bar Curl": "https://www.youtube.com/results?search_query=Reverse-Grip%20EZ-Bar%20Curl%20exercise%20tutorial",
  "Roman Chair Leg Raise": "https://www.youtube.com/results?search_query=Roman%20Chair%20Leg%20Raise%20exercise%20tutorial",
  "Rope Face Pull": "https://www.youtube.com/results?search_query=Rope%20Face%20Pull%20exercise%20tutorial",
  "Seated Barbell Shoulder Press": "https://www.youtube.com/results?search_query=Seated%20Barbell%20Shoulder%20Press%20exercise%20tutorial",
  "Seated Calf Raise": "https://www.youtube.com/results?search_query=Seated%20Calf%20Raise%20exercise%20tutorial",
  "Seated DB French Press": "https://www.youtube.com/results?search_query=Seated%20DB%20French%20Press%20exercise%20tutorial",
  "Seated DB Shoulder Press": "https://www.youtube.com/results?search_query=Seated%20DB%20Shoulder%20Press%20exercise%20tutorial",
  "Seated Leg Curl": "https://www.youtube.com/results?search_query=Seated%20Leg%20Curl%20exercise%20tutorial",
  "Single-arm Overhead Cable Triceps Extension": "https://www.youtube.com/results?search_query=Single-arm%20Overhead%20Cable%20Triceps%20Extension%20exercise%20tutorial",
  "Sissy Squat": "https://www.youtube.com/results?search_query=Sissy%20Squat%20exercise%20tutorial",
  "Slow-Eccentric Barbell RDL": "https://www.youtube.com/results?search_query=Slow-Eccentric%20Barbell%20RDL%20exercise%20tutorial",
  "Slow-Eccentric Bayesian Curl": "https://www.youtube.com/results?search_query=Slow-Eccentric%20Bayesian%20Curl%20exercise%20tutorial",
  "Slow-Eccentric DB Curl": "https://www.youtube.com/results?search_query=Slow-Eccentric%20DB%20Curl%20exercise%20tutorial",
  "Slow-Eccentric DB French Press": "https://www.youtube.com/results?search_query=Slow-Eccentric%20DB%20French%20Press%20exercise%20tutorial",
  "Slow-Eccentric DB Incline Curl": "https://www.youtube.com/results?search_query=Slow-Eccentric%20DB%20Incline%20Curl%20exercise%20tutorial",
  "Slow-Eccentric DB RDL": "https://www.youtube.com/results?search_query=Slow-Eccentric%20DB%20RDL%20exercise%20tutorial",
  "Slow-Eccentric DB Scott Curl": "https://www.youtube.com/results?search_query=Slow-Eccentric%20DB%20Scott%20Curl%20exercise%20tutorial",
  "Slow-Eccentric DB Skull Crusher": "https://www.youtube.com/results?search_query=Slow-Eccentric%20DB%20Skull%20Crusher%20exercise%20tutorial",
  "Slow-Eccentric EZ-Bar Skull Crusher": "https://www.youtube.com/results?search_query=Slow-Eccentric%20EZ-Bar%20Skull%20Crusher%20exercise%20tutorial",
  "Slow-Eccentric Glute-Ham Raise": "https://www.youtube.com/results?search_query=Slow-Eccentric%20Glute-Ham%20Raise%20exercise%20tutorial",
  "Smith Machine JM Press": "https://www.youtube.com/results?search_query=Smith%20Machine%20JM%20Press%20exercise%20tutorial",
  "Smith Machine Lunge": "https://www.youtube.com/results?search_query=Smith%20Machine%20Lunge%20exercise%20tutorial",
  "Smith Machine Reverse Lunge": "https://www.youtube.com/results?search_query=Smith%20Machine%20Reverse%20Lunge%20exercise%20tutorial",
  "Smith Machine Squat": "https://www.youtube.com/results?search_query=Smith%20Machine%20Squat%20exercise%20tutorial",
  "Snatch-Grip RDL": "https://www.youtube.com/results?search_query=Snatch-Grip%20RDL%20exercise%20tutorial",
  "Spider Curl": "https://www.youtube.com/results?search_query=Spider%20Curl%20exercise%20tutorial",
  "Standing Calf Raise": "https://www.youtube.com/results?search_query=Standing%20Calf%20Raise%20exercise%20tutorial",
  "Standing DB Arnold Press": "https://www.youtube.com/results?search_query=Standing%20DB%20Arnold%20Press%20exercise%20tutorial",
  "Stomach Vacuums": "https://www.youtube.com/results?search_query=Stomach%20Vacuums%20exercise%20tutorial",
  "Straight-Bar Lat Prayer": "https://www.youtube.com/results?search_query=Straight-Bar%20Lat%20Prayer%20exercise%20tutorial",
  "Super-ROM DB Lateral Raise": "https://www.youtube.com/results?search_query=Super-ROM%20DB%20Lateral%20Raise%20exercise%20tutorial",
  "Super-ROM Overhand Cable Row": "https://www.youtube.com/results?search_query=Super-ROM%20Overhand%20Cable%20Row%20exercise%20tutorial",
  "Swiss Ball Rollout": "https://www.youtube.com/results?search_query=Swiss%20Ball%20Rollout%20exercise%20tutorial",
  "Triceps Diverging Pressdown (Long Rope or 2 Ropes)": "https://www.youtube.com/results?search_query=Triceps%20Diverging%20Pressdown%20%28Long%20Rope%20or%202%20Ropes%29%20exercise%20tutorial",
  "Triceps Pressdown (Bar)": "https://www.youtube.com/results?search_query=Triceps%20Pressdown%20%28Bar%29%20exercise%20tutorial",
  "Triceps Pressdown (Rope)": "https://www.youtube.com/results?search_query=Triceps%20Pressdown%20%28Rope%29%20exercise%20tutorial",
  "Upright Row": "https://www.youtube.com/results?search_query=Upright%20Row%20exercise%20tutorial",
  "Wide-Grip Band-Assisted Pull-Up": "https://www.youtube.com/results?search_query=Wide-Grip%20Band-Assisted%20Pull-Up%20exercise%20tutorial",
  "Wide-Grip Lat Pulldown": "https://www.youtube.com/results?search_query=Wide-Grip%20Lat%20Pulldown%20exercise%20tutorial",
  "Incline Machine Chest Press": "https://www.youtube.com/results?search_query=Incline%20Machine%20Chest%20Press%20exercise%20tutorial",
  "Iso-Lateral Chest Press": "https://www.youtube.com/results?search_query=Iso-Lateral%20Chest%20Press%20exercise%20tutorial",
  "Iso-Lateral Incline Press": "https://www.youtube.com/results?search_query=Iso-Lateral%20Incline%20Press%20exercise%20tutorial",
  "Iso-Lateral High Row": "https://www.youtube.com/results?search_query=Iso-Lateral%20High%20Row%20exercise%20tutorial",
  "Iso-Lateral Low Row": "https://www.youtube.com/results?search_query=Iso-Lateral%20Low%20Row%20exercise%20tutorial",
  "Viking Press": "https://www.youtube.com/results?search_query=Viking%20Press%20exercise%20tutorial",
  "Smith Machine Overhead Press": "https://www.youtube.com/results?search_query=Smith%20Machine%20Overhead%20Press%20exercise%20tutorial",
  "Machine Preacher Curl": "https://www.youtube.com/results?search_query=Machine%20Preacher%20Curl%20exercise%20tutorial",
  "Seated Dip Machine": "https://www.youtube.com/results?search_query=Seated%20Dip%20Machine%20exercise%20tutorial",
  "Machine Overhead Tricep Extension": "https://www.youtube.com/results?search_query=Machine%20Overhead%20Tricep%20Extension%20exercise%20tutorial",
  "Pendulum Squat": "https://www.youtube.com/results?search_query=Pendulum%20Squat%20exercise%20tutorial",
  "Vertical Leg Press": "https://www.youtube.com/results?search_query=Vertical%20Leg%20Press%20exercise%20tutorial",
  "Glute Drive Machine": "https://www.youtube.com/results?search_query=Glute%20Drive%20Machine%20exercise%20tutorial",
  "Smith Machine Hip Thrust": "https://www.youtube.com/results?search_query=Smith%20Machine%20Hip%20Thrust%20exercise%20tutorial",
  "Standing Single-Leg Curl": "https://www.youtube.com/results?search_query=Standing%20Single-Leg%20Curl%20exercise%20tutorial",
  "Reverse Hyperextension": "https://www.youtube.com/results?search_query=Reverse%20Hyperextension%20exercise%20tutorial",
  "Machine Glute Kickback": "https://www.youtube.com/results?search_query=Machine%20Glute%20Kickback%20exercise%20tutorial",
  "Cable Glute Kickback": "https://www.youtube.com/results?search_query=Cable%20Glute%20Kickback%20exercise%20tutorial",
  "Machine Back Extension": "https://www.youtube.com/results?search_query=Machine%20Back%20Extension%20exercise%20tutorial",
  "Machine Torso Rotation": "https://www.youtube.com/results?search_query=Machine%20Torso%20Rotation%20exercise%20tutorial",
};
