import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import { registerSW } from "virtual:pwa-register";

// Registers the service worker generated by vite-plugin-pwa. This is what
// lets the app itself (not just its data) load with no signal — the app
// shell gets precached on first successful load, then served from cache
// on every load after that, updating automatically in the background.
registerSW({ immediate: true });

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
